### ISSUE TITLE
Re-enable playwright tests skipped since global components were replaced

### ISSUE THREAD

**Issue by seanes** [digdir/dialogporten-frontend#1497]
There are some playwright tests that are `skipped` in Arbeidsflate after we introduced global components from `altinn-components`. These should be revisited and modified / updated and enabled.

**Comment by mbacherycz** [comment]
Some tests scenarios are failing because of the application is breaking after we switched to Altinn Components.
I created two tickets and commented out tests that should be later uncommented to maintain the coverage:
https://github.com/digdir/dialogporten-frontend/issues/1562
https://github.com/digdir/dialogporten-frontend/issues/1559
